AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'gemfiles/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/MultilineOperationIndentation:
  Enabled: false

# Standardrb handles these

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/BlockLength:
  Max: 30

Style/Alias:
  Enabled: false

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
