AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'gemfiles/*'

# Following this cop's advice makes Appraisal's generated gemfiles too wordy
Gemspec/DevelopmentDependencies:
  Enabled: false

# Following this cop's advice breaks my sqlite3 add_development_dependency hack
# to use 1.6 on ruby 3.2
Gemspec/RubyVersionGlobalsUsage:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 40
  Exclude:
    - spec/textual_order_raw_spec.rb
    - spec/execute_queries_spec.rb

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

# Standardrb handles these

Layout/ArgumentAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/Alias:
  Enabled: false

Style/MultilineTernaryOperator:
  Exclude:
    - spec/textual_order_raw_spec.rb

Style/QuotedSymbols:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false
