AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'gemfiles/*'

# Following this cop makes Appraisal's generated gemfiles too wordy
Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

# Standardrb handles these

Layout/ArgumentAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/Alias:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false
