# To build for a version of ruby and active_record, run e.g.:

# docker compose build --build-arg ruby_version=3.0.6 --build-arg activerecord_version=6.1
# docker compose run --rm app bash
# docker compose down

services:
  app:
    build:
      dockerfile: Dockerfile
      args:
        - ruby_version=3.0.6
        - activerecord_version=6.1
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy
  mysql:
    platform: linux/amd64
    image: mysql:8-debian
    environment:
      - MYSQL_ROOT_PASSWORD=Password123
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -pPassword123" ]
      interval: 2s
      timeout: 5s
      retries: 15
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=Password123
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 15
volumes:
  mysqldata:
  pgdata:
