name: CI

on: push

jobs:
  test:
    name: CI Ruby ${{ matrix.ruby-version }} AR ${{ matrix.activerecord-version }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        ruby-version: ['3.1', '3.2.0-preview3']
        activerecord-version: ['6.1', '7.0', '7.1']
        exclude:
          # Rails 7's gemspec requires ruby >= 2.7
          - ruby-version: '2.6'
            activerecord-version: '7.0'
          # Rails 5.x is unlikely ever to support ruby >= 3.0
          # https://github.com/rails/rails/issues/40938#issuecomment-751569171
          - ruby-version: '3.0'
            activerecord-version: '5.0'
          - ruby-version: '3.0'
            activerecord-version: '5.1'
          - ruby-version: '3.0'
            activerecord-version: '5.2'
          - ruby-version: '3.1'
            activerecord-version: '5.0'
          - ruby-version: '3.1'
            activerecord-version: '5.1'
          - ruby-version: '3.1'
            activerecord-version: '5.2'
          - ruby-version: '3.2.0-preview3'
            activerecord-version: '5.0'
          - ruby-version: '3.2.0-preview3'
            activerecord-version: '5.1'
          - ruby-version: '3.2.0-preview3'
            activerecord-version: '5.2'


    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install gems
      env:
        MATRIX_ACTIVERECORD_VERSION: ${{ matrix.activerecord-version }}
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/activerecord_${MATRIX_ACTIVERECORD_VERSION}.gemfile"
        gem install bundler
        bundle install --verbose

    - name: Run tests
      env:
        MATRIX_ACTIVERECORD_VERSION: ${{ matrix.activerecord-version }}
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/activerecord_${MATRIX_ACTIVERECORD_VERSION}.gemfile"
        bundle exec rake

    - name: Run standardrb
      env:
        MATRIX_ACTIVERECORD_VERSION: ${{ matrix.activerecord-version }}
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/activerecord_${MATRIX_ACTIVERECORD_VERSION}.gemfile"
        bundle exec standardrb

    - name: Run rubocop
      env:
        MATRIX_ACTIVERECORD_VERSION: ${{ matrix.activerecord-version }}
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/activerecord_${MATRIX_ACTIVERECORD_VERSION}.gemfile"
        bundle exec rubocop
