name: CI

on: push

jobs:
  test:
    name: CI for Ruby ${{ matrix.ruby-version }} / ActiveRecord ${{ matrix.activerecord-version }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.1'] # TODO: enable 2.6, 3.0 (disabled for performance while developing)
        activerecord-version: ['5.0', '5.2', '6.1', '7.0'] # TODO: enable 5.1, 6.0 (again, performance) -- used Appraisal to generate gemfiles

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install gems
      env:
        MATRIX_ACTIVERECORD_VERSION: ${{ matrix.activerecord-version }}
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/activerecord_${MATRIX_ACTIVERECORD_VERSION}.gemfile"
        gem install bundler
        bundle install

    - name: Run tests
      env:
        MATRIX_ACTIVERECORD_VERSION: ${{ matrix.activerecord-version }}
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/activerecord_${MATRIX_ACTIVERECORD_VERSION}.gemfile"
        bundle exec rake test

    - name: Run rubocop
      run: rubocop
