name: CI

on: push

jobs:
  test:
    name: CI Ruby ${{ matrix.ruby-version }} AR ${{ matrix.activerecord-version }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        ruby-version: ['2.6', '2.7', '3.0', '3.1']
        activerecord-version: ['5.0', '5.1', '5.2', '6.0', '6.1', '7.0']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install gems
      env:
        MATRIX_ACTIVERECORD_VERSION: ${{ matrix.activerecord-version }}
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/activerecord_${MATRIX_ACTIVERECORD_VERSION}.gemfile"
        gem install bundler
        bundle install

    - name: Run tests
      env:
        MATRIX_ACTIVERECORD_VERSION: ${{ matrix.activerecord-version }}
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/activerecord_${MATRIX_ACTIVERECORD_VERSION}.gemfile"
        bundle exec rake

    - name: Run standardrb
      env:
        MATRIX_ACTIVERECORD_VERSION: ${{ matrix.activerecord-version }}
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/activerecord_${MATRIX_ACTIVERECORD_VERSION}.gemfile"
        bundle exec standardrb

    - name: Run rubocop
      env:
        MATRIX_ACTIVERECORD_VERSION: ${{ matrix.activerecord-version }}
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/activerecord_${MATRIX_ACTIVERECORD_VERSION}.gemfile"
        bundle exec rubocop
