name: CI

on: push

jobs:
  test:
    name: CI Ruby ${{ matrix.ruby-version }} AR ${{ matrix.activerecord-version }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        ruby-version: ['2.7.8']
        activerecord-version: ['5.0', '5.1', '5.2', '6.0', '6.1', '7.0', '7.1']

    steps:
    - name: Cleanup
      uses: Automodality/action-clean@v1

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: docker compose --progress=plain build --build-arg ruby_version=${{ matrix.ruby-version }} --build-arg activerecord_version=${{ matrix.activerecord-version }}

    - name: Run standardrb
      run: docker compose run --rm --no-deps app bundle exec standardrb

    - name: Run rubocop
      run: docker compose run --rm --no-deps app bundle exec rubocop

    - name: Up
      run: docker compose --progress=plain up -d

    - name: Run tests, mysql2
      run: docker compose run --rm app bundle exec rake RSPEC_ADAPTER=mysql2

    - name: Run tests, postgresql
      run: docker compose run --rm app bundle exec rake RSPEC_ADAPTER=postgresql

    - name: Run tests, sqlite3
      run: docker compose run --rm app bundle exec rake RSPEC_ADAPTER=sqlite
