name: CI

on: push

jobs:
  test:
    name: CI for Ruby ${{ matrix.ruby-version }} / ActiveRecord ${{ matrix.activerecord-version }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.1']
        activerecord-version: ['5.2', '6.1', '7.0']
        include:
          - ruby-version: '2.6'
            activerecord-version: '5.0'
          - ruby-version: '2.6'
            activerecord-version: '5.1'
          - ruby-version: '3.0'
            activerecord-version: '6.0'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install gems
      env:
        MATRIX_ACTIVERECORD_VERSION: ${{ matrix.activerecord-version }}
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/activerecord_${MATRIX_ACTIVERECORD_VERSION}.gemfile"
        gem install bundler
        bundle install

    - name: Run tests
      env:
        MATRIX_ACTIVERECORD_VERSION: ${{ matrix.activerecord-version }}
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/activerecord_${MATRIX_ACTIVERECORD_VERSION}.gemfile"
        bundle exec rake test

    - name: Run standardrb
      env:
        MATRIX_ACTIVERECORD_VERSION: ${{ matrix.activerecord-version }}
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/activerecord_${MATRIX_ACTIVERECORD_VERSION}.gemfile"
        bundle exec standardrb

    - name: Run rubocop
      env:
        MATRIX_ACTIVERECORD_VERSION: ${{ matrix.activerecord-version }}
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/activerecord_${MATRIX_ACTIVERECORD_VERSION}.gemfile"
        bundle exec rubocop
