name: CI

on: push

jobs:
  test:
    name: CI Ruby ${{ matrix.ruby-version }} AR ${{ matrix.activerecord-version }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        #ruby-version: ['2.6', '2.7', '3.0', '3.1', '3.2']
        #activerecord-version: ['5.0', '5.1', '5.2', '6.0', '6.1', '7.0', '7.1']
        ruby-version: ['2.7', '3.2']
        activerecord-version: ['5.2', '6.1']
        exclude:
          # Rails 7's gemspec requires ruby >= 2.7
          - ruby-version: '2.6'
            activerecord-version: '7.0'
          # Rails 5.x is unlikely ever to support ruby >= 3.0
          # https://github.com/rails/rails/issues/40938#issuecomment-751569171
          - ruby-version: '3.0'
            activerecord-version: '5.0'
          - ruby-version: '3.0'
            activerecord-version: '5.1'
          - ruby-version: '3.0'
            activerecord-version: '5.2'
          - ruby-version: '3.1'
            activerecord-version: '5.0'
          - ruby-version: '3.1'
            activerecord-version: '5.1'
          - ruby-version: '3.1'
            activerecord-version: '5.2'
          - ruby-version: '3.2'
            activerecord-version: '5.0'
          - ruby-version: '3.2'
            activerecord-version: '5.1'
          - ruby-version: '3.2'
            activerecord-version: '5.2'
          # This can't install sqlite3 and I have no idea why
          - ruby-version: '3.2'
            activerecord-version: '7.1'

    steps:
    - name: Cleanup
      uses: Automodality/action-clean@v1

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: docker compose build --build-arg ruby_version=${{ matrix.ruby-version }} --build-arg activerecord_version=${{ matrix.activerecord-version }}

    - name: Run standardrb
      run: bundle exec standardrb

    - name: Run rubocop
      run: bundle exec rubocop

    - name: Run tests
      run: bundle exec rake
